services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ic_sso
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5040:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c '
      apt-get update &&
      apt-get install -y pgagent &&
      docker-entrypoint.sh postgres
      '
    networks:
      - keycloak-network
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/ic_sso
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: sso.sifc.sn
      KC_HOSTNAME_ADMIN: sso.sifc.sn
      KC_FEATURES: hostname
      KC_HTTP_ENABLED: "false"
      KC_HOSTNAME_STRICT: true
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    volumes:
      - /etc/letsencrypt/live/sso.sifc.sn/fullchain.pem:/etc/x509/https/tls.crt
      - /etc/letsencrypt/live/sso.sifc.sn/privkey.pem:/etc/x509/https/tls.key
    ports:
      - "8083:8080"
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    command: ["start"]

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge